export const formConfigurations = [
  {
    grand_label: "Full Name",
    input_id: "fullname",
    input_type: "text",
    input_help: "Your full name will be confirmed with your ID through a confirmation process.",
    action_button_label: "Next",
  },
  {
    grand_label: "Do you currently provide a product or offer a service to public?",
    input_id: "workingYesNo",
    input_type: "radio",
    input_help: "",
    radioLabels: ["Yes", "No"],
    action_button_label: "Next",
  },
  {
    grand_label: "Do you currently produce a product?",
    input_id: "producingYesNo",
    input_type: "radio",
    input_help: "We just need the name of the product you produce. Details come later!",
    radioLabels: ["Yes", "No"],
    action_button_label: "Next",
  },
  {
    grand_label: "Complete name or title of your main product",
    input_id: "product1title",
    input_type: "text",
    input_help: "Please enter the name of your main product. You can add or remove products later.",
    action_button_label: "Next",
  },
  {
    grand_label: "Do you currently provide a service to the public?",
    input_id: "hasService",
    input_type: "radio",
    input_help: "",
    radioLabels: ["Yes", "No"],
    action_button_label: "Next",
  },
  {
    grand_label: "Complete name or title of the service you offer",
    input_id: "serviceName",
    input_type: "text",
    input_help: "",
    action_button_label: "Next",
  },
  {
    grand_label: "Do you work alone or with others?",
    input_id: "hasUnit",
    input_type: "radio",
    input_help: "In case you work alone, a new unit and new working council will be registered. If you already work with others, you will be added to an existing production unit.",
    radioLabels: ["I work in a team", "I work alone"],
    action_button_label: "Next",
  },
  {
    grand_label: "Enter the name of your production unit",
    input_id: "currentProductionUnit",
    input_type: "list",
    input_help: "Enter the name of the unit currently registered on Unicorn from the dropdown list.",
    action_button_label: "Next",
  },
  {
    grand_label: "Set or decide a name for your production unit",
    input_id: "newProductionUnitName",
    input_type: "text",
    input_help: "",
    action_button_label: "Next",
  },
  {
    grand_label: "Set a name for your working council",
    input_id: "councilName",
    input_type: "text",
    input_help: "A working council is responsible for the economy of the production unit. You can change this name later.",
    action_button_label: "Save and got to dashboard",
  },
  // Add more form configurations as needed
];
